// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/signal.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TradeSignal_SendSignal_FullMethodName = "/proto.TradeSignal/SendSignal"
)

// TradeSignalClient is the client API for TradeSignal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TradeSignalClient interface {
	SendSignal(ctx context.Context, in *WhaleSignal, opts ...grpc.CallOption) (*Ack, error)
}

type tradeSignalClient struct {
	cc grpc.ClientConnInterface
}

func NewTradeSignalClient(cc grpc.ClientConnInterface) TradeSignalClient {
	return &tradeSignalClient{cc}
}

func (c *tradeSignalClient) SendSignal(ctx context.Context, in *WhaleSignal, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, TradeSignal_SendSignal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradeSignalServer is the server API for TradeSignal service.
// All implementations must embed UnimplementedTradeSignalServer
// for forward compatibility.
type TradeSignalServer interface {
	SendSignal(context.Context, *WhaleSignal) (*Ack, error)
	mustEmbedUnimplementedTradeSignalServer()
}

// UnimplementedTradeSignalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTradeSignalServer struct{}

func (UnimplementedTradeSignalServer) SendSignal(context.Context, *WhaleSignal) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendSignal not implemented")
}
func (UnimplementedTradeSignalServer) mustEmbedUnimplementedTradeSignalServer() {}
func (UnimplementedTradeSignalServer) testEmbeddedByValue()                     {}

// UnsafeTradeSignalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradeSignalServer will
// result in compilation errors.
type UnsafeTradeSignalServer interface {
	mustEmbedUnimplementedTradeSignalServer()
}

func RegisterTradeSignalServer(s grpc.ServiceRegistrar, srv TradeSignalServer) {
	// If the following call pancis, it indicates UnimplementedTradeSignalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TradeSignal_ServiceDesc, srv)
}

func _TradeSignal_SendSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhaleSignal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeSignalServer).SendSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeSignal_SendSignal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeSignalServer).SendSignal(ctx, req.(*WhaleSignal))
	}
	return interceptor(ctx, in, info, handler)
}

// TradeSignal_ServiceDesc is the grpc.ServiceDesc for TradeSignal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TradeSignal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TradeSignal",
	HandlerType: (*TradeSignalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendSignal",
			Handler:    _TradeSignal_SendSignal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/signal.proto",
}
